# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FullCircle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FullCircle
	pod 'CellDataCoupler', '2.2.0'

  target 'FullCircleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
